/***
  @module ape
*/
#include <stddef.h>
#include <lua.h>
#include <lauxlib.h>
#include <apr_errno.h>
#include "moon.h"
#include "ape.h"


#define DEF( e ) \
  static int ape_status_is_ ## e( lua_State* L ) { \
    apr_status_t status = luaL_checkint( L, 1 ); \
    return APR_STATUS_IS_ ## e( status ); \
  }

#define REG( e ) { "is_" #e, ape_status_is_ ## e },


#ifdef APR_STATUS_IS_ENOSTAT
DEF( ENOSTAT )
#  define REG_APE_IS_ENOSTAT REG( ENOSTAT )
#else
#  define REG_APE_IS_ENOSTAT
#endif

#ifdef APR_STATUS_IS_ENOPOOL
DEF( ENOPOOL )
#  define REG_APE_IS_ENOPOOL REG( ENOPOOL )
#else
#  define REG_APE_IS_ENOPOOL
#endif

#ifdef APR_STATUS_IS_EBADDATE
DEF( EBADDATE )
#  define REG_APE_IS_EBADDATE REG( EBADDATE )
#else
#  define REG_APE_IS_EBADDATE
#endif

#ifdef APR_STATUS_IS_EINVALSOCK
DEF( EINVALSOCK )
#  define REG_APE_IS_EINVALSOCK REG( EINVALSOCK )
#else
#  define REG_APE_IS_EINVALSOCK
#endif

#ifdef APR_STATUS_IS_ENOPROC
DEF( ENOPROC )
#  define REG_APE_IS_ENOPROC REG( ENOPROC )
#else
#  define REG_APE_IS_ENOPROC
#endif

#ifdef APR_STATUS_IS_ENOTIME
DEF( ENOTIME )
#  define REG_APE_IS_ENOTIME REG( ENOTIME )
#else
#  define REG_APE_IS_ENOTIME
#endif

#ifdef APR_STATUS_IS_ENODIR
DEF( ENODIR )
#  define REG_APE_IS_ENODIR REG( ENODIR )
#else
#  define REG_APE_IS_ENODIR
#endif

#ifdef APR_STATUS_IS_ENOLOCK
DEF( ENOLOCK )
#  define REG_APE_IS_ENOLOCK REG( ENOLOCK )
#else
#  define REG_APE_IS_ENOLOCK
#endif

#ifdef APR_STATUS_IS_ENOPOLL
DEF( ENOPOLL )
#  define REG_APE_IS_ENOPOLL REG( ENOPOLL )
#else
#  define REG_APE_IS_ENOPOLL
#endif

#ifdef APR_STATUS_IS_ENOSOCKET
DEF( ENOSOCKET )
#  define REG_APE_IS_ENOSOCKET REG( ENOSOCKET )
#else
#  define REG_APE_IS_ENOSOCKET
#endif

#ifdef APR_STATUS_IS_ENOTHREAD
DEF( ENOTHREAD )
#  define REG_APE_IS_ENOTHREAD REG( ENOTHREAD )
#else
#  define REG_APE_IS_ENOTHREAD
#endif

#ifdef APR_STATUS_IS_ENOTHDKEY
DEF( ENOTHDKEY )
#  define REG_APE_IS_ENOTHDKEY REG( ENOTHDKEY )
#else
#  define REG_APE_IS_ENOTHDKEY
#endif

#ifdef APR_STATUS_IS_EGENERAL
DEF( EGENERAL )
#  define REG_APE_IS_EGENERAL REG( EGENERAL )
#else
#  define REG_APE_IS_EGENERAL
#endif

#ifdef APR_STATUS_IS_ENOSHMAVAIL
DEF( ENOSHMAVAIL )
#  define REG_APE_IS_ENOSHMAVAIL REG( ENOSHMAVAIL )
#else
#  define REG_APE_IS_ENOSHMAVAIL
#endif

#ifdef APR_STATUS_IS_EBADIP
DEF( EBADIP )
#  define REG_APE_IS_EBADIP REG( EBADIP )
#else
#  define REG_APE_IS_EBADIP
#endif

#ifdef APR_STATUS_IS_EBADMASK
DEF( EBADMASK )
#  define REG_APE_IS_EBADMASK REG( EBADMASK )
#else
#  define REG_APE_IS_EBADMASK
#endif

#ifdef APR_STATUS_IS_EDSOOPEN
DEF( EDSOOPEN )
#  define REG_APE_IS_EDSOOPEN REG( EDSOOPEN )
#else
#  define REG_APE_IS_EDSOOPEN
#endif

#ifdef APR_STATUS_IS_EABSOLUTE
DEF( EABSOLUTE )
#  define REG_APE_IS_EABSOLUTE REG( EABSOLUTE )
#else
#  define REG_APE_IS_EABSOLUTE
#endif

#ifdef APR_STATUS_IS_ERELATIVE
DEF( ERELATIVE )
#  define REG_APE_IS_ERELATIVE REG( ERELATIVE )
#else
#  define REG_APE_IS_ERELATIVE
#endif

#ifdef APR_STATUS_IS_EINCOMPLETE
DEF( EINCOMPLETE )
#  define REG_APE_IS_EINCOMPLETE REG( EINCOMPLETE )
#else
#  define REG_APE_IS_EINCOMPLETE
#endif

#ifdef APR_STATUS_IS_EABOVEROOT
DEF( EABOVEROOT )
#  define REG_APE_IS_EABOVEROOT REG( EABOVEROOT )
#else
#  define REG_APE_IS_EABOVEROOT
#endif

#ifdef APR_STATUS_IS_EBADPATH
DEF( EBADPATH )
#  define REG_APE_IS_EBADPATH REG( EBADPATH )
#else
#  define REG_APE_IS_EBADPATH
#endif

#ifdef APR_STATUS_IS_EPATHWILD
DEF( EPATHWILD )
#  define REG_APE_IS_EPATHWILD REG( EPATHWILD )
#else
#  define REG_APE_IS_EPATHWILD
#endif

#ifdef APR_STATUS_IS_ESYMNOTFOUND
DEF( ESYMNOTFOUND )
#  define REG_APE_IS_ESYMNOTFOUND REG( ESYMNOTFOUND )
#else
#  define REG_APE_IS_ESYMNOTFOUND
#endif

#ifdef APR_STATUS_IS_EPROC_UNKNOWN
DEF( EPROC_UNKNOWN )
#  define REG_APE_IS_EPROC_UNKNOWN REG( EPROC_UNKNOWN )
#else
#  define REG_APE_IS_EPROC_UNKNOWN
#endif

#ifdef APR_STATUS_IS_ENOTENOUGHENTROPY
DEF( ENOTENOUGHENTROPY )
#  define REG_APE_IS_ENOTENOUGHENTROPY REG( ENOTENOUGHENTROPY )
#else
#  define REG_APE_IS_ENOTENOUGHENTROPY
#endif

#ifdef APR_STATUS_IS_INCHILD
DEF( INCHILD )
#  define REG_APE_IS_INCHILD REG( INCHILD )
#else
#  define REG_APE_IS_INCHILD
#endif

#ifdef APR_STATUS_IS_INPARENT
DEF( INPARENT )
#  define REG_APE_IS_INPARENT REG( INPARENT )
#else
#  define REG_APE_IS_INPARENT
#endif

#ifdef APR_STATUS_IS_DETACH
DEF( DETACH )
#  define REG_APE_IS_DETACH REG( DETACH )
#else
#  define REG_APE_IS_DETACH
#endif

#ifdef APR_STATUS_IS_NOTDETACH
DEF( NOTDETACH )
#  define REG_APE_IS_NOTDETACH REG( NOTDETACH )
#else
#  define REG_APE_IS_NOTDETACH
#endif

#ifdef APR_STATUS_IS_CHILD_DONE
DEF( CHILD_DONE )
#  define REG_APE_IS_CHILD_DONE REG( CHILD_DONE )
#else
#  define REG_APE_IS_CHILD_DONE
#endif

#ifdef APR_STATUS_IS_CHILD_NOTDONE
DEF( CHILD_NOTDONE )
#  define REG_APE_IS_CHILD_NOTDONE REG( CHILD_NOTDONE )
#else
#  define REG_APE_IS_CHILD_NOTDONE
#endif

#ifdef APR_STATUS_IS_TIMEUP
DEF( TIMEUP )
#  define REG_APE_IS_TIMEUP REG( TIMEUP )
#else
#  define REG_APE_IS_TIMEUP
#endif

#ifdef APR_STATUS_IS_INCOMPLETE
DEF( INCOMPLETE )
#  define REG_APE_IS_INCOMPLETE REG( INCOMPLETE )
#else
#  define REG_APE_IS_INCOMPLETE
#endif

#ifdef APR_STATUS_IS_BADCH
DEF( BADCH )
#  define REG_APE_IS_BADCH REG( BADCH )
#else
#  define REG_APE_IS_BADCH
#endif

#ifdef APR_STATUS_IS_BADARG
DEF( BADARG )
#  define REG_APE_IS_BADARG REG( BADARG )
#else
#  define REG_APE_IS_BADARG
#endif

#ifdef APR_STATUS_IS_EOF
DEF( EOF )
#  define REG_APE_IS_EOF REG( EOF )
#else
#  define REG_APE_IS_EOF
#endif

#ifdef APR_STATUS_IS_NOTFOUND
DEF( NOTFOUND )
#  define REG_APE_IS_NOTFOUND REG( NOTFOUND )
#else
#  define REG_APE_IS_NOTFOUND
#endif

#ifdef APR_STATUS_IS_ANONYMOUS
DEF( ANONYMOUS )
#  define REG_APE_IS_ANONYMOUS REG( ANONYMOUS )
#else
#  define REG_APE_IS_ANONYMOUS
#endif

#ifdef APR_STATUS_IS_FILEBASED
DEF( FILEBASED )
#  define REG_APE_IS_FILEBASED REG( FILEBASED )
#else
#  define REG_APE_IS_FILEBASED
#endif

#ifdef APR_STATUS_IS_KEYBASED
DEF( KEYBASED )
#  define REG_APE_IS_KEYBASED REG( KEYBASED )
#else
#  define REG_APE_IS_KEYBASED
#endif

#ifdef APR_STATUS_IS_EINIT
DEF( EINIT )
#  define REG_APE_IS_EINIT REG( EINIT )
#else
#  define REG_APE_IS_EINIT
#endif

#ifdef APR_STATUS_IS_ENOTIMPL
DEF( ENOTIMPL )
#  define REG_APE_IS_ENOTIMPL REG( ENOTIMPL )
#else
#  define REG_APE_IS_ENOTIMPL
#endif

#ifdef APR_STATUS_IS_EMISMATCH
DEF( EMISMATCH )
#  define REG_APE_IS_EMISMATCH REG( EMISMATCH )
#else
#  define REG_APE_IS_EMISMATCH
#endif

#ifdef APR_STATUS_IS_EBUSY
DEF( EBUSY )
#  define REG_APE_IS_EBUSY REG( EBUSY )
#else
#  define REG_APE_IS_EBUSY
#endif

#ifdef APR_STATUS_IS_EACCES
DEF( EACCES )
#  define REG_APE_IS_EACCES REG( EACCES )
#else
#  define REG_APE_IS_EACCES
#endif

#ifdef APR_STATUS_IS_EEXIST
DEF( EEXIST )
#  define REG_APE_IS_EEXIST REG( EEXIST )
#else
#  define REG_APE_IS_EEXIST
#endif

#ifdef APR_STATUS_IS_ENAMETOOLONG
DEF( ENAMETOOLONG )
#  define REG_APE_IS_ENAMETOOLONG REG( ENAMETOOLONG )
#else
#  define REG_APE_IS_ENAMETOOLONG
#endif

#ifdef APR_STATUS_IS_ENOENT
DEF( ENOENT )
#  define REG_APE_IS_ENOENT REG( ENOENT )
#else
#  define REG_APE_IS_ENOENT
#endif

#ifdef APR_STATUS_IS_ENOTDIR
DEF( ENOTDIR )
#  define REG_APE_IS_ENOTDIR REG( ENOTDIR )
#else
#  define REG_APE_IS_ENOTDIR
#endif

#ifdef APR_STATUS_IS_ENOSPC
DEF( ENOSPC )
#  define REG_APE_IS_ENOSPC REG( ENOSPC )
#else
#  define REG_APE_IS_ENOSPC
#endif

#ifdef APR_STATUS_IS_ENOMEM
DEF( ENOMEM )
#  define REG_APE_IS_ENOMEM REG( ENOMEM )
#else
#  define REG_APE_IS_ENOMEM
#endif

#ifdef APR_STATUS_IS_EMFILE
DEF( EMFILE )
#  define REG_APE_IS_EMFILE REG( EMFILE )
#else
#  define REG_APE_IS_EMFILE
#endif

#ifdef APR_STATUS_IS_ENFILE
DEF( ENFILE )
#  define REG_APE_IS_ENFILE REG( ENFILE )
#else
#  define REG_APE_IS_ENFILE
#endif

#ifdef APR_STATUS_IS_EBADF
DEF( EBADF )
#  define REG_APE_IS_EBADF REG( EBADF )
#else
#  define REG_APE_IS_EBADF
#endif

#ifdef APR_STATUS_IS_EINVAL
DEF( EINVAL )
#  define REG_APE_IS_EINVAL REG( EINVAL )
#else
#  define REG_APE_IS_EINVAL
#endif

#ifdef APR_STATUS_IS_ESPIPE
DEF( ESPIPE )
#  define REG_APE_IS_ESPIPE REG( ESPIPE )
#else
#  define REG_APE_IS_ESPIPE
#endif

#ifdef APR_STATUS_IS_EAGAIN
DEF( EAGAIN )
#  define REG_APE_IS_EAGAIN REG( EAGAIN )
#else
#  define REG_APE_IS_EAGAIN
#endif

#ifdef APR_STATUS_IS_EINTR
DEF( EINTR )
#  define REG_APE_IS_EINTR REG( EINTR )
#else
#  define REG_APE_IS_EINTR
#endif

#ifdef APR_STATUS_IS_ENOTSOCK
DEF( ENOTSOCK )
#  define REG_APE_IS_ENOTSOCK REG( ENOTSOCK )
#else
#  define REG_APE_IS_ENOTSOCK
#endif

#ifdef APR_STATUS_IS_ECONNREFUSED
DEF( ECONNREFUSED )
#  define REG_APE_IS_ECONNREFUSED REG( ECONNREFUSED )
#else
#  define REG_APE_IS_ECONNREFUSED
#endif

#ifdef APR_STATUS_IS_EINPROGRESS
DEF( EINPROGRESS )
#  define REG_APE_IS_EINPROGRESS REG( EINPROGRESS )
#else
#  define REG_APE_IS_EINPROGRESS
#endif

#ifdef APR_STATUS_IS_ECONNABORTED
DEF( ECONNABORTED )
#  define REG_APE_IS_ECONNABORTED REG( ECONNABORTED )
#else
#  define REG_APE_IS_ECONNABORTED
#endif

#ifdef APR_STATUS_IS_ECONNRESET
DEF( ECONNRESET )
#  define REG_APE_IS_ECONNRESET REG( ECONNRESET )
#else
#  define REG_APE_IS_ECONNRESET
#endif

#ifdef APR_STATUS_IS_ETIMEDOUT
DEF( ETIMEDOUT )
#  define REG_APE_IS_ETIMEDOUT REG( ETIMEDOUT )
#else
#  define REG_APE_IS_ETIMEDOUT
#endif

#ifdef APR_STATUS_IS_EHOSTUNREACH
DEF( EHOSTUNREACH )
#  define REG_APE_IS_EHOSTUNREACH REG( EHOSTUNREACH )
#else
#  define REG_APE_IS_EHOSTUNREACH
#endif

#ifdef APR_STATUS_IS_ENETUNREACH
DEF( ENETUNREACH )
#  define REG_APE_IS_ENETUNREACH REG( ENETUNREACH )
#else
#  define REG_APE_IS_ENETUNREACH
#endif

#ifdef APR_STATUS_IS_EFTYPE
DEF( EFTYPE )
#  define REG_APE_IS_EFTYPE REG( EFTYPE )
#else
#  define REG_APE_IS_EFTYPE
#endif

#ifdef APR_STATUS_IS_EPIPE
DEF( EPIPE )
#  define REG_APE_IS_EPIPE REG( EPIPE )
#else
#  define REG_APE_IS_EPIPE
#endif

#ifdef APR_STATUS_IS_EXDEV
DEF( EXDEV )
#  define REG_APE_IS_EXDEV REG( EXDEV )
#else
#  define REG_APE_IS_EXDEV
#endif

#ifdef APR_STATUS_IS_EAFNOSUPPORT
DEF( EAFNOSUPPORT )
#  define REG_APE_IS_EAFNOSUPPORT REG( EAFNOSUPPORT )
#else
#  define REG_APE_IS_EAFNOSUPPORT
#endif



APE_API void ape_errno_setup( lua_State* L ) {
  /***
    Error handling
    @section errors
  */
  luaL_Reg const ape_errno_functions[] = {
    REG_APE_IS_ENOSTAT
    REG_APE_IS_ENOPOOL
    REG_APE_IS_EBADDATE
    REG_APE_IS_EINVALSOCK
    REG_APE_IS_ENOPROC
    REG_APE_IS_ENOTIME
    REG_APE_IS_ENODIR
    REG_APE_IS_ENOLOCK
    REG_APE_IS_ENOPOLL
    REG_APE_IS_ENOSOCKET
    REG_APE_IS_ENOTHREAD
    REG_APE_IS_ENOTHDKEY
    REG_APE_IS_EGENERAL
    REG_APE_IS_ENOSHMAVAIL
    REG_APE_IS_EBADIP
    REG_APE_IS_EBADMASK
    REG_APE_IS_EDSOOPEN
    REG_APE_IS_EABSOLUTE
    REG_APE_IS_ERELATIVE
    REG_APE_IS_EINCOMPLETE
    REG_APE_IS_EABOVEROOT
    REG_APE_IS_EBADPATH
    REG_APE_IS_EPATHWILD
    REG_APE_IS_ESYMNOTFOUND
    REG_APE_IS_EPROC_UNKNOWN
    REG_APE_IS_ENOTENOUGHENTROPY
    REG_APE_IS_INCHILD
    REG_APE_IS_INPARENT
    REG_APE_IS_DETACH
    REG_APE_IS_NOTDETACH
    REG_APE_IS_CHILD_DONE
    REG_APE_IS_CHILD_NOTDONE
    REG_APE_IS_TIMEUP
    REG_APE_IS_INCOMPLETE
    REG_APE_IS_BADCH
    REG_APE_IS_BADARG
    REG_APE_IS_EOF
    REG_APE_IS_NOTFOUND
    REG_APE_IS_ANONYMOUS
    REG_APE_IS_FILEBASED
    REG_APE_IS_KEYBASED
    REG_APE_IS_EINIT
    REG_APE_IS_ENOTIMPL
    REG_APE_IS_EMISMATCH
    REG_APE_IS_EBUSY
    REG_APE_IS_EACCES
    REG_APE_IS_EEXIST
    REG_APE_IS_ENAMETOOLONG
    REG_APE_IS_ENOENT
    REG_APE_IS_ENOTDIR
    REG_APE_IS_ENOSPC
    REG_APE_IS_ENOMEM
    REG_APE_IS_EMFILE
    REG_APE_IS_ENFILE
    REG_APE_IS_EBADF
    REG_APE_IS_EINVAL
    REG_APE_IS_ESPIPE
    REG_APE_IS_EAGAIN
    REG_APE_IS_EINTR
    REG_APE_IS_ENOTSOCK
    REG_APE_IS_ECONNREFUSED
    REG_APE_IS_EINPROGRESS
    REG_APE_IS_ECONNABORTED
    REG_APE_IS_ECONNRESET
    REG_APE_IS_ETIMEDOUT
    REG_APE_IS_EHOSTUNREACH
    REG_APE_IS_ENETUNREACH
    REG_APE_IS_EFTYPE
    REG_APE_IS_EPIPE
    REG_APE_IS_EXDEV
    REG_APE_IS_EAFNOSUPPORT
    { NULL, NULL }
  };
  moon_register( L, ape_errno_functions );
}

