#!/usr/bin/lua

--  buildsh -- a portable and flexible build system
--  Copyright (C) 2013  Philipp Janda
--
--  This program is free software: you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation, either version 3 of the License, or
--  (at your option) any later version.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see <http://www.gnu.org/licenses/>.


local function readfile( in_f )
  local f = assert( io.open( in_f, "r" ) )
  local s = assert( f:read( "*a" ) )
  f:close()
  return s
end

assert( arg[ 1 ], "need Lua file(s) as arguments" )
for _,f in ipairs( arg ) do
  local s = readfile( f )
  local out = assert( io.open( f..".h", "w" ) )
  out:write( [[
/* Contents of Lua file ]] .. f .. [[ as a character array because the
 * length of character literals is very limited in ISO C.
 * Generated by `lua lua2inc.lua ]] .. f .. [['.
 */
{ ]] )
  for i = 1, #s do
    out:write( tostring( s:byte( i ) ),
               i == #s and "" or ",",
               i % 10 == 0 and "\n" or " " )
  end
  out:write( "}\n" )
  out:close()
end

